### ISSUE TITLE
Adding a manual button for capturing photos

### ISSUE THREAD

**Issue by matijaozetski9y** [AppliedRecognition/ID-Card-Camera#1]
I would like to add a manual "capture photo" button next to the torch button at the bottom of the screen. 

Is this possible to implement given the current library?

**Comment by jakubdolejs** [comment]
Hello @matijaozetski9y,

It's possible but it kind of defeats the purpose of the library, which snaps the picture automatically when a card or barcode is detected. You may be better off capturing the image using [UIImagePickerController](https://developer.apple.com/documentation/uikit/uiimagepickercontroller).

If you still want to add a manual capture button you can extend [CardDetectionViewController](https://github.com/AppliedRecognition/ID-Card-Camera/blob/master/Sources/IDCardCamera/CardDetectionViewController.swift), override the `viewDidLoad()` function and add the button there. I'm not sure what you'd like the button to trigger though.
